development:
  adapter: mysql2
  encoding: utf8
  database: sts_dev
  pool: 5
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: sts_test
  pool: 5
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: sts_prod
  pool: 5
  #socket: /var/run/mysqld/mysql.sock
